apiVersion: v1
kind: Service
metadata:
  name: {{ include "apricot-proxy.fullname" . }}
  labels:
    {{- include "apricot-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: ldap
    {{- if .Values.apricot.ldap.enableTls }}
    - port: {{ .Values.apricot.ldap.tlsPort }}
      targetPort: {{ .Values.apricot.ldap.tlsPort }}
      protocol: TCP
      name: ldaps
    {{- end }}
  selector:
    {{- include "apricot-proxy.selectorLabels" . | nindent 4 }}