# openproject/templates/database-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-database-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  database.yml: |
    # The ERB templating within this YAML will be processed by Rails inside the container.
    <%
    DATABASE_OPTIONS = %w[
      url
      database
      encoding
      pool
      username
      password
      passfile
      sslmode
      sslcompression
      sslcert
      sslkey
      sslpassword
      sslrootcert
      sslcrl
      ssl_min_protocol_version
      application_name
      statement_timeout
      channel_binding
      connect_timeout
      client_encoding
      keepalives
      keepalives_idle
      keepalives_interval
      keepalives_count
      gssencmode
      replication
    ].freeze

    DATABASE_VARIABLES = %w[
      statement_timeout
    ]

    DATABASE_DEFAULTS = {
      # Fallback to unprefixed DATABASE_URL if present
      'url' => ENV['DATABASE_URL'],
      'statement_timeout' => ENV.fetch("POSTGRES_STATEMENT_TIMEOUT", "90s"),
      'encoding' => 'unicode',
      'application_name' => 'openproject',
    }.freeze
    %>

    production:
      adapter: postgresql
      encoding: unicode
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      host: <%= ENV["OPENPROJECT_DB_HOST"] || ENV["DATABASE_HOST"] %>
      port: <%= ENV["OPENPROJECT_DB_PORT"] || ENV["DATABASE_PORT"] || 5432 %>
      database: <%= ENV["OPENPROJECT_DB_NAME"] || ENV["DATABASE_NAME"] %>
      username: <%= ENV["OPENPROJECT_DB_USER"] || ENV["DATABASE_USER"] %>
      password: <%= ENV["OPENPROJECT_DB_PASS"] || ENV["DATABASE_PASSWORD"] %>
      schema_search_path: public
      connect_timeout: 5
      variables:
        statement_timeout: 60000
        lock_timeout: 10000
        idle_in_transaction_session_timeout: 10000